define([], function() {
  return {
    "issueTypeValues": ["Electrical", "Plumbing", "HVAC", "Safety Hazard"],
    "severityValues": ["Low", "Medium", "High", "Urgent"],
    "statusValues": ["Reported","Pending Verification", "Verified", "Resolved","Closed", "Unable to Resolve"],
    
    "newRequestIntro": "To submit a new facilities issue please fill out the name of the requestor (if not you) and a description of the issue. Please be as specific as possible. Your issue will be reviewed and assigned to the appropriate department.",
    "issueTypeLabel": "Issue Type",
    "locationLabel": "Location",
    "reportedDateLabel": "Reported Date",
    "severityLabel": "Severity",
    "issueDescriptionLabel": "Issue Description",
    "imageLabel": "Image",
    "reportedByLabel": "Reported By",
    "equipmentIdLabel": "Equipment ID or Asset ID",
    "assigneeLabel": "Assigned To",
    "verificationDateLabel": "Verification Date",
    "requestStatusLabel": "Status",
    "additionalCommentsLabel": "Comments",
    "estimatedResolutionDateLabel": "Estimated Resolution Date",
    "resolvedByLabel": "Resolved By",
    "resolutionDateLabel": "Resolution Date",
    "resolutionDescriptionLabel": "Resolution Description",
    "reviewDateLabel": "Review Date",
    "reviewedByLabel": "Reviewer",
    "reviewNotesLabel": "Reviewer Notes",
    "inspectionDateLabel": "Next Inspection Date",
    "editRequestHeader": "Edit Request",
    "errorHeader": "The form is not valid. Please fix the following errors and try again.",
    
    "reportIssueButton": "Report Issue",
    "cancelButton": "Cancel",
    "editReportButton": "Edit Report",
    "updateReportButton": "Update Report",
    "editReviewButton"  : "Edit Review",
    "invalidateReportButton": "Invalidate Report",
    "validateReportButton": "Validate Report",
    "unableToResolveButton": "Unable to Resolve",
    "completedButton": "Completed",
    "editResolutionButton": "Edit Resolution",
    
    "reportedIssueHeader": "Reported Issue",
    "reviewAssignHeader": "Review and Assign",
    "issueResolutionHeader" : "Issue Resolution",    
  }
});